---
# title: "COMPUTATIONAL STATISTICS AND GPU ACCELERATION"
# author: "ANDREAS S. BAMPOURIS"
# date: "July 2025"
site: "bookdown::bookdown_site"
documentclass: book
classoption: "twoside"
fontsize: 12pt
linestretch: 1.5
mainfont: "Times New Roman"
bibliography: bibliography.bib
biblio-style: agsm
link-citations: yes
geometry: "left=2.5cm, right=2.5cm, top=2.5cm, bottom=2.5cm"
output:
  bookdown::pdf_book:
    includes:
      before_body: titlepage.tex
    toc_depth: 3
---

\tableofcontents
\listoftables
\listoffigures

\mainmatter

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

library(knitr)
library(data.table)
library(magrittr)
library(ggplot2)
library(kableExtra)
```

```{r custom_functions, include=FALSE}
extract_mean_sd <- function(dat, col) {
  dat[, (col) := gsub("\\[|\\]", "", get(col))]
  stats <- lapply(strsplit(dat[[col]], ","), function(x) {
    x <- as.numeric(x)
    list(mean = mean(x), sd = sd(x))
  })
  stats_dt <- data.table::rbindlist(stats)
  dat[, paste0(col, "_mean") := stats_dt$mean]
  dat[, paste0(col, "_sd") := stats_dt$sd]
  return(dat)
}

get_falkon_metrics <- function(dat, size) {
  get_row <- function(rt) dat[run_type == rt & n_samples == size]
  
  cpu <- get_row("Falkon (CPU)")
  gpu <- get_row("Falkon (GPU)")
  
  format_pm <- function(mean, sd) sprintf("%.2f ± %.2f", mean, sd)
  
  list(
    train_cpu = format_pm(cpu$train_time, cpu$train_sd),
    train_gpu = format_pm(gpu$train_time, gpu$train_sd),
    train_speedup = sprintf("%.0f", cpu$train_time / gpu$train_time),
    
    pred_cpu = format_pm(cpu$pred_time, cpu$pred_sd),
    pred_gpu = format_pm(gpu$pred_time, gpu$pred_sd),
    pred_speedup = sprintf("%.0f", cpu$pred_time / gpu$pred_time)
  )
}
```
